import Head from 'next/head'
import Image from 'next/image'
import CallToActionWithVideo from '../src/components/CallToActionWithVideo/CallToActionWithVideo'
import Navbar from '../src/components/Navbar/Navbar';
import styles from './index.module.scss';
import Features from '../src/components/Features/Features';
import CallToActionWithAnnotation from '../src/components/CallToActionWithAnnotation/CallToActionWithAnnotation';
import { Container } from '@chakra-ui/react';

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar></Navbar>
            <Container maxW={'3xl'}>
                <CallToActionWithAnnotation></CallToActionWithAnnotation>
            </Container>
            <Container maxW={'5xl'}>
                <Features></Features>
            </Container>

        </div>
    )
}
